name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter test
      - run: npm install --prefix ./functions
      - run: flutter build web
#      - run: mkdir functions/public
#      - run: mv -f build/web/{.[!.],}* functions/public/
#      - uses: w9jds/firebase-action@master
#        with:
#          args: deploy --only functions
#        env:
#          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECIAL_CONSIDERATION }}'